#=========================== Filebeat inputs =============================
filebeat.inputs:
  # 收集nginx日志
  - type: log
    enabled: true
    paths:
      - /data_ssd2/logs/nginx/*.log
    # 日志是json开启这个
    json.keys_under_root: true
    json.overwrite_keys: true
    json.add_error_key: true

#-------------------------- Redis output ------------------------------
output.redis:
  hosts: ["host"]   #输出到redis的机器
  password: "password"
  key: "nginx_logs"   #redis中日志数据的key值ֵ
  db: 1
  timeout: 10


